<?php
	http_response_code(302);
	header('Location: https://docs.google.com/forms/d/1DWi2dP8SvfBr6kJQtKzOi2OH13NAvzs54MvKiEuHZ78/viewform');
?>
<!DOCTYPE html>
<html>
<head>

		<meta charset="utf-8">
		<title>Linux workshop за начинаещи</title>
		<meta content='width=device-width, initial-scale=0.8, maximum-scale=0.8, user-scalable=no' name='viewport'>
		<meta name="description" content="Linux workshop за начинаещи" />

		<!-- REDIRECTING STARTS -->
		<!-- Generated by http://insider.zone/tools/client-side-url-redirect-generator/ -->
		<link rel="canonical" href="https://docs.google.com/forms/d/1DWi2dP8SvfBr6kJQtKzOi2OH13NAvzs54MvKiEuHZ78/viewform"/>
		<noscript>
			<meta http-equiv="refresh" content="0;URL=https://docs.google.com/forms/d/1DWi2dP8SvfBr6kJQtKzOi2OH13NAvzs54MvKiEuHZ78/viewform">
		</noscript>
		<!--[if lt IE 9]><script type="text/javascript">var IE_fix=true;</script><![endif]-->
		<script type="text/javascript">
			var url = "https://docs.google.com/forms/d/1DWi2dP8SvfBr6kJQtKzOi2OH13NAvzs54MvKiEuHZ78/viewform";
			if(typeof IE_fix != "undefined") {
				// IE8 and lower fix to pass the http referer
				document.write(""); // Don't remove this line or appendChild() will fail because it is called before document.onload to make the redirect as fast as possible. Nobody will see this text, it is only a tech fix.
				var referLink = document.createElement("a");
				referLink.href = url;
				document.body.appendChild(referLink);
				referLink.click();
			} else {
				// All other browsers
				window.location.replace(url);
			}
		</script>
		<!-- REDIRECTING ENDS -->

</head>
<body>
</body>
</html>
